#!/bin/bash

# https://www.youtube.com/watch?v=7qd5sqazD7k

name=$1
compliment=$2

user=$(whoami)
date=$(date)
whereami=$(pwd)

echo "Good Morning $name!!"
sleep 1
echo "You're looking good today $name!!"
sleep 1
echo "You have the best $compliment I've ever seen $name!!"
sleep 2

echo "You are currently logged in as $user and you are in the directory $whereami. Also today is: $date"


# chmod +x bestdayever.sh
# ./bestdayever.sh


